require 'digest'
require 'securerandom'

require 'clock/controls'

require 'packaging/debian/schemas/controls/digest'

require 'packaging/debian/schemas/controls/architecture'
require 'packaging/debian/schemas/controls/codename'
require 'packaging/debian/schemas/controls/component'
require 'packaging/debian/schemas/controls/suite'
require 'packaging/debian/schemas/controls/time'

require 'packaging/debian/schemas/controls/random'

require 'packaging/debian/schemas/controls/rfc822/data'
require 'packaging/debian/schemas/controls/rfc822/text'

require 'packaging/debian/schemas/controls/package/data'
require 'packaging/debian/schemas/controls/package'
require 'packaging/debian/schemas/controls/package/file'
require 'packaging/debian/schemas/controls/package/text'
require 'packaging/debian/schemas/controls/package/minimal'
require 'packaging/debian/schemas/controls/package/alternate'
require 'packaging/debian/schemas/controls/package/alternate/data'
require 'packaging/debian/schemas/controls/package/alternate/text'

require 'packaging/debian/schemas/controls/package_index'
require 'packaging/debian/schemas/controls/package_index/text'
require 'packaging/debian/schemas/controls/package_index/alternate'
require 'packaging/debian/schemas/controls/package_index/minimal'
require 'packaging/debian/schemas/controls/package_index/entry/data'
require 'packaging/debian/schemas/controls/package_index/entry'
require 'packaging/debian/schemas/controls/package_index/entry/text'
require 'packaging/debian/schemas/controls/package_index/entry/alternate'
require 'packaging/debian/schemas/controls/package_index/entry/minimal'

require 'packaging/debian/schemas/controls/release/data'
require 'packaging/debian/schemas/controls/release'
require 'packaging/debian/schemas/controls/release/file'
require 'packaging/debian/schemas/controls/release/minimal'
require 'packaging/debian/schemas/controls/release/text'
require 'packaging/debian/schemas/controls/release/alternate'
require 'packaging/debian/schemas/controls/release/alternate/data'
require 'packaging/debian/schemas/controls/release/alternate/file'
require 'packaging/debian/schemas/controls/release/alternate/text'
